---
title: "plot_cutsites"
author: "Max Dudek"
output: pdf_document
---

```{r setup, include=FALSE}
suppressPackageStartupMessages({
  library(tidyverse)
  library(ComplexHeatmap)
  library(circlize)
  library(knitr)
})
```

```{r}
# FP_METHOD <- "PRINT_local_cutsites_geq10_no_gaussian"
# FP_METHOD <- "PRINT_local_cutsites_geq10"
FP_METHOD <- "PRINT_beta_cloglog"
if (grepl("no_gaussian", FP_METHOD, fixed = TRUE) | grepl("PRINT_beta", FP_METHOD, fixed = TRUE)) {
  FP_SCORE_LIM <- c(0,1)
} else {
  FP_SCORE_LIM <- c(-3, 3)
}

genotype_colors <- c("#d33682", "#6c71c4", "#2aa198")
```


```{r}
fpQTLs_FDR5 <- read.delim(paste0("../regression/FP_methods/", FP_METHOD,
                                 "/regression_results/fpQTLs_covariates_FDR5.txt"))
fpscore_matrix <- readRDS(paste0("../regression/FP_methods/", FP_METHOD,
                                 "/data/fpscore_matrix_fpQTLs_with_covariates.Rds"))
fpscore_matrix_normalized <- readRDS(paste0("../regression/FP_methods/", FP_METHOD,
                                 "/data/fpscore_matrix_normalized_fpQTLs_with_covariates.Rds"))
genotype_matrix <- readRDS(paste0("../regression/FP_methods/", FP_METHOD,
                          "/data/genotype_matrix_fpQTLs_with_covariates.Rds"))
```


```{r}
rsIDs <- fpQTLs_FDR5 %>% arrange(pval) %>% head(25) %>% pull(variant_id)

cutsites <- readRDS(paste0("cutsites/", FP_METHOD, "/fpQTL_cutsites.Rds"))
cutsites <- lapply(cutsites, dplyr::select, sample, position, num_insertions, bias, expected_insertions, corrected_insertions)
```

```{r}
rs <- names(cutsites)[1]

cutsites[[rs]]
```



```{r}
get_df <- function(rs) {
  data.frame(
    fpscore_normalized = fpscore_matrix_normalized[rs,] %>% na.omit(),
    fpscore = fpscore_matrix[rs,] %>% na.omit(),
    genotype = genotype_matrix[rs,] %>% na.omit()
  ) %>%
    rownames_to_column("sample") %>%
    arrange(sample)
}

get_sample_order <- function(rs) {
   get_df(rs) %>%
    arrange(genotype, fpscore_normalized) %>%
    pull(sample) ->
    sample_order
  
  return(sample_order)
}

get_title <- function(rs) {
  rs.info <- fpQTLs_FDR5 %>% filter(variant_id == rs)
  
  title <- paste0(rs, " (", rs.info$variant_chrom, ":", rs.info$variant_pos, "), beta = ",
                  round(rs.info$beta, 3), ", -log10(p) = ", round(-log10(rs.info$pval), 3))
  
  return(title)
}

get_df(rs)
```


```{r}
plot_boxplot <- function(rs, normalized = TRUE, ...) {
  y.aes = ifelse(normalized, "fpscore_normalized", "fpscore")
  y.lab = ifelse(normalized, "Normalized FP score", "FP score")
  
  get_df(rs) %>%
    ggplot(aes(x = as.factor(genotype), y = .data[[y.aes]])) +
    geom_boxplot(aes(fill = as.factor(genotype))) + 
    geom_jitter(height = 0, width = 0.1, ...) +
    scale_fill_manual(name = "Genotype", values = genotype_colors, labels = 0:2) +
    xlab("Genotype") + 
    ylab(y.lab) +
    ggtitle(get_title(rs)) +
    theme_classic()
}
```

# Plot transparent boxplot for schematic figure
```{r fig.width=6, fig.height=4}
rs <- "rs55838121"
get_df(rs) %>%
    ggplot(aes(x = as.factor(genotype), y = fpscore_normalized)) +
    geom_boxplot(aes(fill = as.factor(genotype))) + 
    geom_jitter(height = 0, width = 0.1) +
    scale_fill_manual(name = "Genotype", values = genotype_colors, labels = 0:2) +
    xlab("Genotype") + 
    ylab("Footprint score") +
    ggtitle(get_title(rs)) +
    theme_classic() +
    theme(panel.background = element_rect(fill='transparent'),
        plot.background = element_rect(fill='transparent', color=NA))
ggsave("figures/boxplot_example_transparent.png", 
       width = 6, height = 4, bg = "transparent")
  
```


# MANUSCRIPT - Figure 5B
```{r fig.width=4, fig.height=3}
plot_boxplot("rs12740374", size = 1)
ggsave("figures/rs12740374_boxplot.png", width = 4, height = 3, units = "in", dpi = 300)
```




```{r fig.width=6, fig.height=4}
rs <- rsIDs[13]
plot_boxplot(rs, normalized = FALSE)

```
```{r fig.width=10, fig.height=25}
plot_corrected_cutsites_pileup <- function(rs, ncol=7) {
  # Order samples by fp score
  sample_order <- get_sample_order(rs)
  nrow <- length(sample_order) %/% ncol

  cutsites[[rs]] %>%
    inner_join(get_df(rs), join_by(sample)) ->
    df
  
  df %>%
    mutate(sample = factor(sample, levels = sample_order)) %>%
    filter(!is.na(sample)) %>% # Remove samples with NA fp score
    arrange(genotype, sample) %>%
    ggplot() +
    geom_bar(aes(x = position, y = corrected_insertions, fill = as.factor(genotype)),
             stat = "identity") +
    geom_hline(yintercept = 0) +
    geom_point(x = 0, y = 0, size = 0.5, shape = 4) +
    geom_text(
      aes(label = round(fpscore_normalized, 2)),
      x = 0, y = 4, size = 2.5) +
    xlim(c(-75, 75)) +
    ylim(c(-5, 6)) +
    scale_fill_manual(values = genotype_colors, name = "Genotype") +
    facet_wrap(~as.factor(sample), ncol = ncol) +
    theme_classic() +
    coord_fixed(12) +
    ggtitle(get_title(rs))
}

# plot_cutsites_pileup(names(cutsites)[16])
plot_corrected_cutsites_pileup("rs12740374")
``` 



```{r fig.width=10, fig.height=20}
plot_cutsites_pileup <- function(rs, ncol=7) {
  # Order samples by fp score
  sample_order <- get_sample_order(rs)
  nrow <- length(sample_order) %/% ncol

  cutsites[[rs]] %>%
    inner_join(get_df(rs), join_by(sample)) ->
    df
  
  df %>%
    mutate(sample = factor(sample, levels = sample_order)) %>%
    filter(!is.na(sample)) %>% # Remove samples with NA fp score
    arrange(genotype, sample) %>%
    ggplot() +
    geom_bar(aes(x = position, y = num_insertions, fill = as.factor(genotype)),
             stat = "identity") +
    geom_point(x = 0, y = 0, size = 1, shape = "triangle") +
    geom_text(
      aes(label = round(fpscore_normalized, 2)),
      x = 0, y = 18, size = 2.5) +
    xlim(c(-75, 75)) +
    ylim(c(-1, 20)) +
    scale_fill_manual(values = genotype_colors, name = "Genotype") +
    facet_wrap(~as.factor(sample), ncol = ncol) +
    theme_classic() +
    coord_fixed(4) +
    ggtitle(get_title(rs))
}

# plot_cutsites_pileup(names(cutsites)[16])
plot_cutsites_pileup(rs)
``` 

Bulk cutsites
```{r fig.width=7, fig.height=6}
plot_bulk_cutsites_pileup <- function(rs) {
  cutsites[[rs]] %>%
    inner_join(get_df(rs), join_by(sample)) ->
    df
  
  df %>%
    filter(!is.na(sample)) %>% # Remove samples with NA fp score
    group_by(position, genotype) %>%
    summarise(num_insertions = sum(num_insertions)) %>%
    ggplot() +
    geom_bar(aes(x = position, y = num_insertions, fill = as.factor(genotype)),
             stat = "identity") +
    geom_point(x = 0, y = 0, size = 2, shape = "triangle") +
    xlim(c(-75, 75)) +
    scale_fill_manual(values = genotype_colors, name = "Genotype") +
    facet_wrap(~as.factor(genotype), ncol = 1, scales = "free_y") +
    theme_classic() +
    theme(legend.position = "none") +
    ggtitle(get_title(rs))
}

# plot_cutsites_pileup(names(cutsites)[16])
plot_bulk_cutsites_pileup("rs12740374")
``` 

```{r fig.width=7, fig.height=6}
plot_bulk_corrected_cutsites_pileup <- function(rs) {
  cutsites[[rs]] %>%
    inner_join(get_df(rs), join_by(sample)) ->
    df
  
  df %>%
    filter(!is.na(sample)) %>% # Remove samples with NA fp score
    group_by(position, genotype) %>%
    summarise(corrected_insertions = sum(corrected_insertions)) %>%
    ggplot() +
    geom_bar(aes(x = position, y = corrected_insertions, fill = as.factor(genotype)),
             stat = "identity") +
    geom_hline(yintercept = 0) +
    geom_point(x = 0, y = 0, size = 2, shape = 4) +
    xlim(c(-75, 75)) +
    scale_fill_manual(values = genotype_colors, name = "Genotype") +
    facet_wrap(~as.factor(genotype), ncol = 1, scales = "free_y") +
    ylab("Bias-corrected insertion counts") +
    xlab("Position") + 
    theme_classic() +
    theme(legend.position = "none") +
    ggtitle(get_title(rs))
}

cutsites[["rs12740374"]]

# plot_bulk_corrected_cutsites_pileup(names(cutsites)[16])
plot_bulk_corrected_cutsites_pileup("rs12740374")
``` 

# MANUSCRIPT - Figure 5C
# Export image
```{r fig.width=5, fig.height=3}
plot_bulk_corrected_cutsites_pileup <- function(rs) {
  cutsites[[rs]] %>%
    inner_join(get_df(rs), join_by(sample)) ->
    df

  df %>%
    filter(!is.na(sample)) %>% # Remove samples with NA fp score
    group_by(position, genotype) %>%
    summarise(corrected_insertions = sum(corrected_insertions)) %>%
    mutate(genotype = as.factor(genotype)) %>%
    ggplot() +
    geom_bar(aes(x = position, y = corrected_insertions, fill = genotype),
             stat = "identity") +
    geom_hline(yintercept = 0) +
    geom_point(x = 0, y = 0, size = 2, shape = 4) +
    xlim(c(-75, 75)) +
    scale_fill_manual(values = genotype_colors, name = "Genotype") +
    facet_wrap(~genotype, ncol = 1, scales = "free_y") +
    ylab("Bias-corrected insertion counts") +
    xlab("Position") + 
    theme_bw() +
    theme(legend.position = "none") + 
    theme(
      strip.background = element_blank(),
      strip.text.x = element_blank(),
      panel.grid.major = element_blank(), panel.grid.minor = element_blank()
    )
}
cutsites[["rs12740374"]]

# plot_bulk_corrected_cutsites_pileup(names(cutsites)[16])
plot_bulk_corrected_cutsites_pileup("rs12740374")
ggsave("figures/rs12740374_bulk_corrected_pileup.png", width = 5, height = 3, units = "in", dpi = 300)
``` 

```{r}
plot_bulk_expected_cutsites_pileup <- function(rs) {
  cutsites[[rs]] %>%
    inner_join(get_df(rs), join_by(sample)) ->
    df
  
  df %>%
    filter(!is.na(sample)) %>% # Remove samples with NA fp score
    arrange(genotype, sample) %>%
    ggplot() +
    geom_bar(aes(x = position, y = expected_insertions, fill = as.factor(genotype)),
             stat = "identity") +
    geom_hline(yintercept = 0) +
    geom_point(x = 0, y = 0, size = 2, shape = 4) +
    xlim(c(-75, 75)) +
    scale_fill_manual(values = genotype_colors, name = "Genotype") +
    facet_wrap(~as.factor(genotype), ncol = 1, scales = "free_y") +
    theme_classic() +
    theme(legend.position = "none") +
    ggtitle(get_title(rs))
}

plot_bulk_expected_cutsites_pileup("rs12740374")
```


ComplexHeatmap 
```{r fig.width=10, fig.height=8}
ht_opt$TITLE_PADDING = unit(c(4, 8), "points")

plot_complex_heatmap <- function(rs) {
  sample_order <- get_sample_order(rs)

  variant_df <- get_df(rs)
  
  complete_df <- 
    data.frame(
      sample = rep(sample_order, each = length(-50:50)),
      position = rep(-50:50, times = length(sample_order))
    )
  
  cutsites[[rs]] %>%
    select(sample, position, num_insertions) %>%
    filter(sample %in% sample_order) %>% # Remove samples where fp_score = NA
    mutate(position = as.integer(position)) %>%
    right_join(complete_df, by = join_by(sample, position)) %>%
    arrange(sample, position) %>%
    replace(is.na(.), 0) %>%
    pivot_wider(names_from = position, values_from = num_insertions) %>%
    arrange(sample) %>%
    column_to_rownames("sample") %>%
    as.matrix() ->
    mat
  
  mat %>%
    Heatmap(
      name = "Tn5 cutsites\n(corrected)",
      row_order = order(variant_df$fpscore_normalized),
      show_row_names = FALSE,
      column_labels = c("-50", rep("", 24), "-25",  rep("", 24), "0",
                        rep("", 24), "25",  rep("", 24), "50"),
      column_names_rot = 0,
      column_title_side = "bottom", column_title = "Position",
      column_order = colnames(mat),
      col = colorRamp2(c(0, 6), c("white", "red")),
      row_split = factor(variant_df$genotype, levels = 0:2),
      row_title = gt_render(
        0:(length(unique(variant_df$genotype))-1),
        halign = 0.5, valign = 0.5,
        padding = unit(c(0, 0, 0, 0), "pt")
      ),
      row_title_gp = gpar(fill = genotype_colors, fontsize = 20, lwd = 0),
      row_gap = unit(5, "mm"),
      right_annotation = rowAnnotation(
        "FP score\n(normalized)" = variant_df$fpscore_normalized,
        col = list("FP score\n(normalized)" = colorRamp2(FP_SCORE_LIM, c("white", "dark green")))
      ),
      width = unit(8, "in"), height = unit(7, "in")
    ) %>%
    draw(
      row_title = gt_render("Genotype", gp = gpar(cex = 1.3)),
      column_title = gt_render(get_title(rs), gp = gpar(cex = 1))
    )
}

plot_complex_heatmap(rs)

```


```{r}
dir.create(file.path("figures", FP_METHOD), showWarnings = FALSE)
```

Plot cutsite pileups
```{r}
pdf(width = 10, height = 20, file.path("figures", FP_METHOD, "pileups.pdf"))
for (rs in names(cutsites)) {
  print(rs)
  print(plot_cutsites_pileup(rs))
}
dev.off()
```

Plot boxplots
```{r}
pdf(width = 6, height = 4, file.path("figures", FP_METHOD, "boxplots.pdf"))
for (rs in names(cutsites)) {
  print(rs)
  print(plot_boxplot(rs, normalized = FALSE))
  print(plot_boxplot(rs, normalized = TRUE))
}
dev.off()
```

Plot complex heatmaps
```{r}
pdf(width = 10, height = 10, file.path("figures", FP_METHOD, "heatmaps.pdf"))
for (rs in names(cutsites)) {
  print(rs)
  print(plot_complex_heatmap(rs))
}
dev.off()
```



